# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '功率测试工具V1.1.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(821, 586)
        self.Vin = QtWidgets.QLCDNumber(Form)
        self.Vin.setGeometry(QtCore.QRect(65, 10, 64, 23))
        self.Vin.setObjectName("Vin")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 45, 51, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(140, 45, 51, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(435, 471, 54, 22))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(435, 10, 381, 371))
        self.textBrowser.setObjectName("textBrowser")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(435, 510, 371, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(535, 550, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(435, 390, 381, 71))
        self.textEdit.setObjectName("textEdit")
        self.Vout = QtWidgets.QLCDNumber(Form)
        self.Vout.setGeometry(QtCore.QRect(65, 40, 64, 23))
        self.Vout.setObjectName("Vout")
        self.Vout_2 = QtWidgets.QLCDNumber(Form)
        self.Vout_2.setGeometry(QtCore.QRect(65, 70, 64, 23))
        self.Vout_2.setObjectName("Vout_2")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(140, 15, 51, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(275, 18, 61, 22))
        self.label.setObjectName("label")
        self.Iin = QtWidgets.QLCDNumber(Form)
        self.Iin.setGeometry(QtCore.QRect(195, 10, 64, 23))
        self.Iin.setObjectName("Iin")
        self.frame_p_t = QtWidgets.QFrame(Form)
        self.frame_p_t.setGeometry(QtCore.QRect(10, 335, 350, 220))
        self.frame_p_t.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_p_t.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_p_t.setObjectName("frame_p_t")
        self.frame_vi_t = QtWidgets.QFrame(Form)
        self.frame_vi_t.setGeometry(QtCore.QRect(10, 105, 350, 220))
        self.frame_vi_t.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_vi_t.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_vi_t.setObjectName("frame_vi_t")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(625, 471, 54, 22))
        self.label_3.setObjectName("label_3")
        self.trigtime = QtWidgets.QTimeEdit(Form)
        self.trigtime.setGeometry(QtCore.QRect(685, 470, 118, 22))
        self.trigtime.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.trigtime.setDisplayFormat("hh:mm:ss:mss")
        self.trigtime.setObjectName("trigtime")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(10, 15, 51, 16))
        self.checkBox.setObjectName("checkBox")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(335, 15, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setGeometry(QtCore.QRect(140, 75, 51, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.Iout = QtWidgets.QLCDNumber(Form)
        self.Iout.setGeometry(QtCore.QRect(195, 40, 64, 23))
        self.Iout.setObjectName("Iout")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 75, 51, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.Vout_3 = QtWidgets.QLCDNumber(Form)
        self.Vout_3.setGeometry(QtCore.QRect(195, 70, 64, 23))
        self.Vout_3.setObjectName("Vout_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(435, 550, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.testtime = QtWidgets.QTimeEdit(Form)
        self.testtime.setGeometry(QtCore.QRect(495, 470, 118, 22))
        self.testtime.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.testtime.setDisplayFormat("hh:mm:ss:mss")
        self.testtime.setTimeSpec(QtCore.Qt.LocalTime)
        self.testtime.setTime(QtCore.QTime(0, 0, 0))
        self.testtime.setObjectName("testtime")

        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(275, 63, 61, 22))
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(335, 60, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(635, 550, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(735, 550, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_2.setText(_translate("Form", "CH2_V"))
        self.checkBox_5.setText(_translate("Form", "CH2_I"))
        self.label_2.setText(_translate("Form", "测试时间："))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">串口打印信息：</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "功率测试"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">串口输入：</span></p></body></html>"))
        self.checkBox_4.setText(_translate("Form", "CH1_I"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">端口号：</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "采样周期："))
        self.checkBox.setText(_translate("Form", "CH1_V"))
        self.checkBox_6.setText(_translate("Form", "CH4_V"))
        self.checkBox_3.setText(_translate("Form", "CH3_V"))
        self.pushButton_2.setText(_translate("Form", "电压测试"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">波特率：</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "停止"))
        self.pushButton_4.setText(_translate("Form", "退出"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())