# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '功率测试工具V1.0.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(822, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Vin = QtWidgets.QLCDNumber(self.centralwidget)
        self.Vin.setGeometry(QtCore.QRect(60, 0, 64, 23))
        self.Vin.setObjectName("Vin")
        self.Iin = QtWidgets.QLCDNumber(self.centralwidget)
        self.Iin.setGeometry(QtCore.QRect(190, 0, 64, 23))
        self.Iin.setObjectName("Iin")
        self.Vout = QtWidgets.QLCDNumber(self.centralwidget)
        self.Vout.setGeometry(QtCore.QRect(60, 30, 64, 23))
        self.Vout.setObjectName("Vout")
        self.Iout = QtWidgets.QLCDNumber(self.centralwidget)
        self.Iout.setGeometry(QtCore.QRect(190, 30, 64, 23))
        self.Iout.setObjectName("Iout")
        self.frame_vi_t = QtWidgets.QFrame(self.centralwidget)
        self.frame_vi_t.setGeometry(QtCore.QRect(5, 95, 350, 220))
        self.frame_vi_t.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_vi_t.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_vi_t.setObjectName("frame_vi_t")
        self.frame_p_t = QtWidgets.QFrame(self.centralwidget)
        self.frame_p_t.setGeometry(QtCore.QRect(5, 325, 350, 220))
        self.frame_p_t.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_p_t.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_p_t.setObjectName("frame_p_t")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 520, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 520, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(330, 5, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.Vout_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.Vout_2.setGeometry(QtCore.QRect(60, 60, 64, 23))
        self.Vout_2.setObjectName("Vout_2")
        self.Vout_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.Vout_3.setGeometry(QtCore.QRect(190, 60, 64, 23))
        self.Vout_3.setObjectName("Vout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 8, 61, 22))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(5, 5, 51, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(5, 35, 51, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(5, 65, 51, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(135, 5, 51, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(135, 35, 51, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(135, 65, 51, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(630, 520, 181, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(430, 0, 381, 371))
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(430, 380, 381, 71))
        self.textEdit.setObjectName("textEdit")
        self.trigtime = QtWidgets.QTimeEdit(self.centralwidget)
        self.trigtime.setGeometry(QtCore.QRect(680, 460, 118, 22))
        self.trigtime.setObjectName("trigtime")
        self.testtime = QtWidgets.QTimeEdit(self.centralwidget)
        self.testtime.setGeometry(QtCore.QRect(490, 460, 118, 22))
        self.testtime.setObjectName("testtime")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 461, 54, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 461, 54, 22))
        self.label_3.setObjectName("label_3")
        self.textBrowser.raise_()
        self.Vin.raise_()
        self.Iin.raise_()
        self.Vout.raise_()
        self.Iout.raise_()
        self.frame_vi_t.raise_()
        self.frame_p_t.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.comboBox.raise_()
        self.Vout_2.raise_()
        self.Vout_3.raise_()
        self.label.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_5.raise_()
        self.checkBox_6.raise_()
        self.progressBar.raise_()
        self.textEdit.raise_()
        self.trigtime.raise_()
        self.testtime.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 23))
        self.menubar.setObjectName("menubar")
        self.menuTX = QtWidgets.QMenu(self.menubar)
        self.menuTX.setObjectName("menuTX")
        self.menuRX = QtWidgets.QMenu(self.menubar)
        self.menuRX.setObjectName("menuRX")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionchongdian = QtWidgets.QAction(MainWindow)
        self.actionchongdian.setObjectName("actionchongdian")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.actiond = QtWidgets.QAction(MainWindow)
        self.actiond.setObjectName("actiond")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action5_2 = QtWidgets.QAction(MainWindow)
        self.action5_2.setObjectName("action5_2")
        self.action5_3 = QtWidgets.QAction(MainWindow)
        self.action5_3.setObjectName("action5_3")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.menuTX.addAction(self.action_4)
        self.menuTX.addAction(self.actiond)
        self.menuRX.addSeparator()
        self.menuRX.addAction(self.actionchongdian)
        self.menuRX.addAction(self.action1)
        self.menuRX.addAction(self.action2)
        self.menuRX.addAction(self.action3)
        self.menuRX.addAction(self.action4)
        self.menuRX.addAction(self.action5)
        self.menuRX.addAction(self.action5_2)
        self.menubar.addAction(self.menuTX.menuAction())
        self.menubar.addAction(self.menuRX.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APP"))
        self.pushButton.setText(_translate("MainWindow", "电流测试"))
        self.pushButton_2.setText(_translate("MainWindow", "电压测试"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">端口号：</span></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "CH1_V"))
        self.checkBox_2.setText(_translate("MainWindow", "CH2_V"))
        self.checkBox_3.setText(_translate("MainWindow", "CH3_V"))
        self.checkBox_4.setText(_translate("MainWindow", "CH1_I"))
        self.checkBox_5.setText(_translate("MainWindow", "CH2_I"))
        self.checkBox_6.setText(_translate("MainWindow", "CH4_V"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">串口打印信息：</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">串口输入：</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "测试时间："))
        self.label_3.setText(_translate("MainWindow", "采样周期："))
        self.menuTX.setTitle(_translate("MainWindow", "TX测试"))
        self.menuRX.setTitle(_translate("MainWindow", "RX测试"))
        self.actionchongdian.setText(_translate("MainWindow", "匹配测试 "))
        self.action_4.setText(_translate("MainWindow", "充电周期"))
        self.actiond.setText(_translate("MainWindow", "匹配测试"))
        self.action1.setText(_translate("MainWindow", "充电稳定性测试"))
        self.action2.setText(_translate("MainWindow", "动态带载测试"))
        self.action3.setText(_translate("MainWindow", "负载升降测试"))
        self.action4.setText(_translate("MainWindow", "负载ON/OFF测试"))
        self.action5.setText(_translate("MainWindow", "带载启动测试"))
        self.action5_2.setText(_translate("MainWindow", "输入电源开关测试"))
        self.action5_3.setText(_translate("MainWindow", "5"))
        self.action6.setText(_translate("MainWindow", "6"))
        self.action7.setText(_translate("MainWindow", "7"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    widget.show()
    sys.exit(app.exec_())
